version: '3.8'

services:
  dataflow-api:
    container_name: backend
    build: .
    command: npm run start-container
    working_dir: /dataflow/backend
    ports:
      - "8000:8000"
    environment:
      - PG_PROD_USERNAME=fishy3legs
      - PG_PROD_PASSWORD=test
      - PG_PROD_DATABASE=dataflow
      - PG_PROD_HOST=postgres
      - DEV_PORT=8000
      - NODE_ENV=production
      - DEV_JWT_SECRET=bB2up3SVkOizhJRZc1PiDi6QojUBloOO

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=fishy3legs
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=dataflow
      - POSTGRES_HOST=postgres


# Create DB with postgres
# link environment variables with dataflow-api service
# 