name: lint dataflow
run-name: ${{ github.actor }} activated linting

on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend # Only applies to run steps

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.6.0

      - name: Install dependenciesgi
        run: npm i

      - uses: reviewdog/action-eslint@v1
