name: lint dataflow
run-name: ${{ github.actor }} activated linting

on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.6.0

      - name: Install dependencies
        run: | 
          cd ./backend
          npm i

      - name: Run eslint
        run: npx eslint .
