name: lint, test, build, and deploy containerized dataflow API to ec2
run-name: ${{ github.actor }} activated ci/cd pipeline

on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend # Only applies to run steps

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.6.0

      - name: Install dependencies
        run: npm i eslint

      - name: Run linting script with eslint
        run: npx eslint .

  # After linting, create application container for testing and deploy
  build-test-deploy:
    needs: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend # Only applies to run steps

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.6.0

    - name: Create image
      run: docker build -t docker.io/fishy3legs/dataflow-api:1.0 .

    - name: Start container with proper test environment variables
      run: docker run -d -name test-container docker.io/fishy3legs/dataflow-api:1.0

    - name: Run tests with application inside test container
      run: docker exec test-container npm run integration-tests

